services:
  minecraft:
    build: .
    ports:
      - "${PORT}:25565"
    container_name: minecraft_server
    volumes:
      - ./server:/server
    stdin_open: true
    tty: true
    command: ["bash", "start.sh"]
