services:
  minecraft:
    build: .
    ports:
      - "25565:25565"
    container_name: minecraft_server
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    command: ["bash", "start.sh"]
